name: API tests

on:
  push:
    branches: [ '008-CICD-Project' ]
  pull_request:
    branches: [ '008-CICD-Project' ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Restore dependencies API Tests
      run: dotnet restore "C:\Windows\System32\actions-runner\_work\ReportPortal.Dashboard.Autotests\ReportPortal.Dashboard.Autotests\ReportPortal.ATM\APITests\APITests.csproj"
      shell: cmd

    - name: Build API Test project
      run: dotnet build --no-restore "C:\Windows\System32\actions-runner\_work\ReportPortal.Dashboard.Autotests\ReportPortal.Dashboard.Autotests\ReportPortal.ATM\APITests\APITests.csproj"
      shell: cmd

  test:
    needs: build
    runs-on: self-hosted

    steps:
    
    - name: Test API
      run: dotnet test "C:\Windows\System32\actions-runner\_work\ReportPortal.Dashboard.Autotests\ReportPortal.Dashboard.Autotests\ReportPortal.ATM\APITests\APITests.csproj"
      shell: cmd
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}