name: .NET CI

on:
  push:
    branches: [ 007-CICD-Pipeline ]
  pull_request:
    branches: [ 007-CICD-Pipeline ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Specify the .NET version

    - name: Restore dependencies
      run: |
        for proj in $(find . -name '*.csproj'); do
          dotnet restore $proj
        done
      shell: bash

    - name: Build
      run: |
        for proj in $(find . -name '*.csproj'); do
          dotnet build $proj --configuration Release --no-restore
        done
      shell: bash

    - name: Test
      run: |
        dotnet test ReportPortal.ATM/APITests/APITests.csproj --no-restore --verbosity normal
        done
      shell: bash
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}

